FROM registry.redhat.io/devspaces/udi-rhel8:3.14

# Switching to root user (setting UID to 0) because next
# commands require root privileges. Universal Developer
# Image default user has UID set to 1000.
USER 0

# add stuff

# Switch back to default user
USER 1000